#!/bin/bash
set -e

adduser --quiet --system ribeye
[ -d /var/log/ribeye ] || (mkdir -p /var/log/ribeye && chown ribeye /var/log/ribeye)
systemd-tmpfiles --create ribeye.conf
systemctl -q daemon-reload
systemctl -q enable ribeye
service ribeye start